### ISSUE TITLE
Accessibility self check result for imsc-hrm

### ISSUE THREAD

**Issue by himorin** [w3c/imsc-hrm#17]
None of the questions in the accessibility questionnaire apply to the IMSC-HRM specification.
For all of the "If ..." rows in the table, the answer is that that they _do not apply_.

Looking at the related [Media Accessibility Checklist](https://www.w3.org/WAI/PF/HTML/wiki/Media_Accessibility_Checklist) linked from the accessibility questionnaire, I think we can say something like:

* The purpose of the IMSC-HRM specification is to allow subtitle and caption authors and providers to verify that the content they provide does not exceed defined complexity levels, so that playback systems can render the content synchronised with the author-specified display times. This supports the delivery and playback of content so that it can meet the CC-* requirements.

**Comment by palemieux** [comment]
@himorin What is the requested action on this issue?

**Comment by himorin** [comment]
closing this per a11y-request issue is closed: https://github.com/w3c/a11y-request/issues/19
