### ISSUE TITLE
privacy and security self review results for IMSC-HRM

### ISSUE THREAD

**Issue by himorin** [w3c/imsc-hrm#19]
This specification has no inherent security or privacy implications.

The algorithm defined within this specification is used for static analysis of a resource. This specification does not define any protocol or interface for obtaining such a resource, and it does not define any interface for exposing the results of the analysis. No personal or sensitive information is processed as part of the algorithm. No information is exposed by the algorithm to any origin. No scripts are loaded or processed as part of the algorithm.

**Comment by palemieux** [comment]
@himorin What is the action on this issue?

**Comment by nigelmegitt** [comment]
See #57
