### ISSUE TITLE
expand IMSC acronym

### ISSUE THREAD

**Issue by samuelweiler** [w3c/imsc-hrm#26]
As a style thing, please expand the IMSC acronym in the abstract (at least) and possibly also in a new introduction section.

**Comment by palemieux** [comment]
A couple of `imsc` missed:

https://github.com/w3c/imsc-hrm/blob/73c052827962ce11e8f882f4d38154999621d7ce/spec/imsc-hrm.html#L224
https://github.com/w3c/imsc-hrm/blob/73c052827962ce11e8f882f4d38154999621d7ce/spec/imsc-hrm.html#L266
https://github.com/w3c/imsc-hrm/blob/73c052827962ce11e8f882f4d38154999621d7ce/spec/imsc-hrm.html#L446
