### ISSUE TITLE
Informal note that address how the HRM applies to customization

### ISSUE THREAD

**Issue by andreastai** [w3c/imsc-hrm#35]
This issue is based on a discussion that started in https://github.com/w3c/imsc-hrm/issues/12 a discussion 

The proposal was as follows (see https://github.com/w3c/imsc-hrm/issues/12#issuecomment-989818373):

> Although customization is out of the scope of TTML/IMSC it is a common use case that before rendering IMSC content the user has some control over styling features such as color and font characteristics. A comment in the IMSC HRM could add that to test rendering of IMSC documents after customization, transformed versions of the original IMSC document with thresholds of styling features (e.g. specific font size) need to be provided to the HRM.

**Comment by andreastai** [comment]
In the course of the discussion, the following proposal was made by @nigelmegitt 

> Implementers of presentation processors should ensure that those processors are able to present Document Instances that meet the HRM constraints, even if user customisation choices, e.g. those defined by [maur], effectively increase the complexity of presentation.

I think this text would be a very good base for an edit.

**Comment by nigelmegitt** [comment]
Thanks @andreastai , if we are using that text as a basis hopefully it will be clear that we are talking about IMSC presentation processors, and _not_ HRM validation processors. If there's doubt we might need to tweak the wording slightly.

**Comment by andreastai** [comment]
@nigelmegitt 

>if we are using that text as a basis hopefully it will be clear that we are talking about IMSC presentation processors, and not HRM validation processors.

I think this should be clear as at the beginning of the text it says:

> Implementers of presentation processors should ensure...

**Comment by nigelmegitt** [comment]
We might just have to define "presentation processors" as a term defined in TTML.
