### ISSUE TITLE
Computation model incomplete?

### ISSUE THREAD

**Issue by aphillips** [w3c/imsc-hrm#37]
https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#paint-text

In discussing the above algorithm in the I18N teleconference of 2022-02-03, the Working Group was concerned that the list of scripts, blocks, and other information seemed incomplete and possibly is an estimate based on some developer's experiences. There seem to be gaps in potential sources of render speed complexity (there is no mention of bidi/right-to-left for example).

Does TT need help with filling in missing values? Is this model complete?

**Comment by aphillips** [comment]
We don't know what you're trying to do and how precisely you thought the HRM needs to be in this regard. It makes it difficult to discern where there are gaps. 

My observation here is that you list like four scripts with one performance level when probably dozens have similar performance. Similarly you call out one of the CJK blocks with a different render performance. It's unclear how HRM arrived at these values. It's also unclear if you want to achieve fairly precise results vs. a broad estimate. Can you clarify what's needed here?

**Comment by nigelmegitt** [comment]
I think a broad estimate is what is needed, but if there are any scripts or blocks that are known to be significantly more or less computationally intensive to render or copy, we should call those out. 

I suspect that the observation of just a small number of scripts reflects the input we have received, but I do not want to state this with any certainty until we've had a think and a dig around - this algorithm and wording has been around for several years.

**Comment by aphillips** [comment]
Rather then speculate, we should probably turn to the rendering experts, such as @behdad.

**Comment by himorin** [comment]
@aphillips (/cc @behdad ) we actually have not get input from script/language dependent rendering experts, so how about to resolve this with keeping existing note which states more script/language dependent complexity parameter could exist and not covered in current list, and seek further input later?

**Comment by behdad** [comment]
Sorry for the late reply. I've studied the computation model and given how rough of an approximation it is, I think it is good enough as it is.

**Comment by aphillips** [comment]
Thanks @behdad. I think we could close this issue.
