### ISSUE TITLE
WG Note cannot be listed as normative reference??

### ISSUE THREAD

**Issue by himorin** [w3c/imsc-hrm#48]
Term code point is [defined by referring i18n-glossary](https://github.com/w3c/imsc-hrm/blob/e286e07dc7ff4d0074e898aaf362f2c948d89ced/spec/imsc-hrm.html#L226), which is non-rectrack and is WG Note.
I believe we cannot mark WG Note as [section F.1 normative reference](https://www.w3.org/TR/imsc-hrm/#normative-references).

**Comment by nigelmegitt** [comment]
In that case I propose that we duplicate the definition and reference the source informatively.
