### ISSUE TITLE
Define 'Presentation Compositor' [TAG review]

### ISSUE THREAD

**Issue by rhiaro** [w3c/imsc-hrm#58]
Please forgive my ignorance as I get up to speed with this work.

The IMSC HRM spec contains the term 'Presentation Compositor' several times but does not link to or define what this is. Could you provide or point me to an explanation?

(cc https://github.com/w3ctag/design-reviews/issues/788)

**Comment by palemieux** [comment]
The Presentation Compositor is one of the processing steps of the HRM -- see Figure 2.

**Comment by rhiaro** [comment]
Aha thanks, that explains why ctrl+f didn't find it.

**Comment by palemieux** [comment]
I suggest reopening this issue since this is something others are likely to run into.

**Comment by himorin** [comment]
Section 6 defines architectural components and their processing diagrams (Figure 2), but marked as non-normative. As above, some of defined components have normative SHALL texts for their behavior. (Also some part of diagrams seem to be only described in section 6, like switching between non-empty ISD and empty ISD?)
Are these (both components and diagrams) better to be normatively described at somewhere else than non-normative section 6??

(note, I lack enough experience on these normativeness, so comments should be wrong...)
