### ISSUE TITLE
A few minor editorial suggestions

### ISSUE THREAD

**Issue by chrisn** [w3c/imsc-hrm#79]
I've just been reviewing the spec and have a few minor suggestions:

1. The Abstract currently talks more about what the spec doesn't do, and I think could explain more about what it does do. I suggest including some of the text from 5.1 Objective.
2. In the Abstract and Scope sections, I think "an Hypothetical" should be "a Hypothetical", as the H is pronounced.
3. In Figure 1 "all IMSC instance document" should be "all IMSC instance documents".
4. In section 6, "sequence of Intermediate Synchronic Documents" is referred to as Ei, but in section 7 it's referred to as En. Should these be the same in both sections?

**Comment by palemieux** [comment]
> In the Abstract and Scope sections, I think "an Hypothetical" should be "a Hypothetical", as the H is pronounced.

Apparently it is a "a":

https://www.merriam-webster.com/dictionary/hypothetical

**Comment by chrisn** [comment]
Some more data: https://books.google.com/ngrams/graph?content=a+hypothetical%2Can+hypothetical&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3
